apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: solareclipsecountdown
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`)
    services:
    - name: solareclipsecountdown
      port: 3000
  tls:
    secretName: solareclipsecountdown-cert
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: solareclipsecountdown-redirect
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`)
    middlewares:
    - name: https-redirect
      namespace: traefik
    services:
    - kind: TraefikService
      name: noop@internal